### PR TITLE
Implement `_init_user_config` function

### PR DESCRIPTION
**Pull request by sergipastor**

### CODE REVIEW

**Comment by asciidiego** [comment]
@sergipastor Could you write some tests for this? I will check this out personally later.

**Comment by asciidiego** [comment]
What about this? @sergipastor

**Review by sergipastor — COMMENTED** [review]
gr8! ;)

**Comment by asciidiego** [comment]
Remember, let's not merge our own PRs! Let's be Trump, not Obama. @sergipastor

**Pull request merged**
